### PR TITLE
9 fix clojure core

### LINKED ISSUE #9: The current bootstrap function does not compile clojure.core and pprint
## Problem

We are not able to compile `clojure.core` and `clojure.pprint` so far.
The rest is compiling properly.

## Suggestion

Once every files can be compiled, update the `build/bootstrap` function to add the magic, clr and clojure dll in the `boostrap`.

### PR DESCRIPTION
**Pull request by skydread1**
close #9 

All the dll files of the `stdlib` can be compiled now except from `clojure.pprint`.

The instructions on how to tests and use `cli-repl` were added to the README as well.

The github action`artifact` now contains the clojure and magic dlls.

`clojure.core` indent fixed

### CODE REVIEW

**Comment by robertluo** [comment]
`magic.api` not compiled?

**Comment by skydread1** [comment]
`magic.api` is compiled. You can see the dlls in the artifact as well.

**Comment by robertluo** [comment]
> `magic.api` is compiled. You can see the dlls in the artifact as well.

Weird, I can not find it using `nos build/bootstrap`

**Comment by skydread1** [comment]
> > `magic.api` is compiled. You can see the dlls in the artifact as well.
> 
> Weird, I can not find it using `nos build/bootstrap`

Is it the only that is not compiled ?

Be sure to use this branch and not master.

**Comment by robertluo** [comment]
> > > `magic.api` is compiled. You can see the dlls in the artifact as well.
> > 
> > 
> > Weird, I can not find it using `nos build/bootstrap`
> 
> Is it the only one that is not compiled ?
Yes. There are 22 files under bootstrap folder, exactly the same number we specified in `build.clj`, however, one additional `clojure.spec.gen.alpha.clj.dll` appears in place of `magic.api`.

> 
> Be sure to use this branch and not master.

**Comment by skydread1** [comment]
> > > > `magic.api` is compiled. You can see the dlls in the artifact as well.
> > > 
> > > 
> > > Weird, I can not find it using `nos build/bootstrap`
> > 
> > 
> > Is it the only one that is not compiled ?
> > Yes. There are 22 files under bootstrap folder, exactly the same number we specified in `build.clj`, however, one additional `clojure.spec.gen.alpha.clj.dll` appears in place of `magic.api`.
> 
> > Be sure to use this branch and not master.

Normally, it should generates more files (I have 47 files in bootstrap). I used `mono` to build.

**Pull request merged**
